---
language: objective-c
cache: pip
os: osx
rvm: 2.3.1
osx_image:
  - xcode9
  - xcode9.1
  - xcode9.2
sudo: required

#install:
    #- sudo -H easy_install pip
    #- sudo -H pip install -I ansible==2.4.0.0
    #- mkdir -p /tmp/roles
    #- "{ echo '[defaults]'; echo 'roles_path = ../:/tmp/roles'; echo 'hash_behaviour=merge'; } >> ansible.cfg"
    #- mkdir -p /tmp/.macos-bootstrap/
    #- "{ echo 'secret_param: true'; echo 'username: \"foo\"'; } >> /tmp/.macos-bootstrap/secrets.yml"
    #- ansible-galaxy install -f -r tests/requirements.yml -p /tmp/roles
script:
  - "./bootstrap.sh $(pwd)/.macos-bootstrap"
  - "./bootstrap.sh $(pwd)/.macos-bootstrap | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
