---
language: objective-c
os: osx
sudo: required
osx_image: xcode9
#  - xcode8.3
#  - xcode8.2
#  - xcode8.1
#  - xcode8
#  - xcode7.3
#  - xcode6.4
#install:
    #- sudo -H easy_install pip
    #- sudo -H pip install -I ansible==2.4.0.0
    #- mkdir -p /tmp/roles
    #- "{ echo '[defaults]'; echo 'roles_path = ../:/tmp/roles'; echo 'hash_behaviour=merge'; } >> ansible.cfg"
    #- mkdir -p /tmp/.macos-bootstrap/
    #- "{ echo 'secret_param: true'; echo 'username: \"foo\"'; } >> /tmp/.macos-bootstrap/secrets.yml"
    #- ansible-galaxy install -f -r tests/requirements.yml -p /tmp/roles
script:
  - "./bootstrap.sh $(pwd)/.macos-bootstrap"
  - "./bootstrap.sh $(pwd)/.macos-bootstrap | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
