---
language: objective-c

cache: pip

os:
  - osx

sudo: required

osx_image: xcode9

#install:
    #- sudo -H easy_install pip
    #- sudo -H pip install -I ansible==2.3.2.0
    #- mkdir -p /tmp/roles
    #- "{ echo '[defaults]'; echo 'roles_path = ../:/tmp/roles'; echo 'hash_behaviour=merge'; } >> ansible.cfg"
    #- mkdir -p /tmp/.macos-bootstrap/
    #- "{ echo 'secret_param: true'; echo 'username: \"foo\"'; } >> /tmp/.macos-bootstrap/secrets.yml"
    #- ansible-galaxy install -f -r tests/requirements.yml -p /tmp/roles

script:
  - "sudo ./bootstrap.sh"
