---
- { src: "https://github.com/feffi/ansible-include-vars.git", name: "feffi.include-vars" }
- { src: "https://github.com/feffi/ansible-git-config.git", name: "feffi.git-config" }
- { src: "https://github.com/feffi/ansible-ssg-config.git", name: "feffi.ssh-config" }
- { src: "https://github.com/feffi/ansible-macos-computername.git", name: "feffi.macos-computername" }
- { src: "https://github.com/feffi/ansible-macos-homebrew.git", name: "feffi.macos-homebrew" }
- { src: "https://github.com/feffi/ansible-macos-defaults.git", name: "feffi.macos-defaults" }
- { src: "https://github.com/feffi/ansible-macos-ssd.git", name: "feffi.macos-ssd" }
- { src: "https://github.com/feffi/ansible-macos-softwareupdate.git", name: "feffi.macos-softwareupdate" }
- { src: "https://github.com/feffi/ansible-macos-avatar.git", name: "feffi.macos-avatar" }
- { src: "https://github.com/feffi/ansible-debug.git", name: "feffi.debug" }
- { src: "https://github.com/feffi/ansible-macos-ohmyzsh.git", name: "feffi.macos-ohmyzsh" }
- { src: "https://github.com/feffi/ansible-macos-dotfiles.git", name: "feffi.macos-dotfiles" }
- { src: "https://github.com/feffi/ansible-macos-settings.git", name: "feffi.macos-settings" }
- { src: "https://github.com/feffi/ansible-macos-dock.git", name: "feffi.macos-dock" }
- { src: "https://github.com/feffi/ansible-macos-sublime.git", name: "feffi.macos-sublime" }
- { src: "https://github.com/feffi/ansible-macos-standby.git", name: "feffi.macos-standby" }
- { src: "https://github.com/feffi/ansible-macos-finder.git", name: "feffi.macos-finder" }
- { src: "https://github.com/feffi/ansible-macos-git-repos.git", name: "feffi.macos-git-repos" }
- { src: "https://github.com/feffi/ansible-macos-pip.git", name: "feffi.macos-pip" }
- { src: "https://github.com/feffi/ansible-macos-timemachine.git", name: "feffi.macos-timemachine" }
- { src: "https://github.com/feffi/ansible-macos-ui.git", name: "feffi.macos-ui" }